# Generated by Django 5.2.3 on 2025-06-19 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("hostname", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.URLField(blank=True, null=True)),
                ("request_path", models.CharField(max_length=500)),
                ("query_params", models.JSONField(default=dict)),
                ("server_mac", models.CharField(blank=True, max_length=17, null=True)),
                ("geolocation", models.JSONField(default=dict)),
                (
                    "trigger_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trigger_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("headers", models.JSONField(default=dict)),
                ("is_local_network", models.BooleanField(default=False)),
                ("via_ngrok", models.BooleanField(default=False)),
                ("response_format", models.CharField(default="json", max_length=20)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="tracking_ap_timesta_99d5ab_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="tracking_ap_ip_addr_3de04d_idx"
                    ),
                    models.Index(
                        fields=["trigger_type"], name="tracking_ap_trigger_8e2b40_idx"
                    ),
                    models.Index(
                        fields=["trigger_method"], name="tracking_ap_trigger_f6f04d_idx"
                    ),
                ],
            },
        ),
    ]
